framework:
    messenger:
        failure_transport: failed
        default_bus: none.bus
        buses:
            none.bus:
                default_middleware: allow_no_handlers
            command.bus:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

            events_async: '%env(MESSENGER_TRANSPORT_DSN)%/events'
            events_sync: 'sync://'

            commands_async: '%env(MESSENGER_TRANSPORT_DSN)%/commands'
            commands_sync: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            App\Twit\Domain\DomainEvent: events_async
